# Generated by Django 4.2.7 on 2024-01-12 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graph_salary_level', models.ImageField(upload_to='images_db/%Y/%m/%d', verbose_name='График уровень зарплат по годам')),
                ('graph_num_vacancy', models.ImageField(upload_to='images_db/%Y/%m/%d', verbose_name='График количество вакансий по годам')),
                ('table', models.TextField(verbose_name='Таблица')),
            ],
        ),
        migrations.CreateModel(
            name='Geography',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graph_salary_level_by_city', models.ImageField(upload_to='images_db/%Y/%m/%d', verbose_name='График уровень зарплат по городам')),
                ('graph_vacancy_fraction_by_city', models.ImageField(upload_to='images_db/%Y/%m/%d', verbose_name='График доля вакансий по городам')),
                ('table', models.TextField(verbose_name='Таблица')),
            ],
        ),
        migrations.CreateModel(
            name='MainPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, verbose_name='Описание профессии')),
                ('photo', models.ImageField(upload_to='images_db/%Y/%m/%d', verbose_name='Фото')),
            ],
        ),
        migrations.CreateModel(
            name='Navigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=25, verbose_name='Заголовок вакансии')),
                ('logo_field', models.ImageField(upload_to='images_db/%Y/%m/%d', verbose_name='Логотип')),
                ('first_menu', models.TextField(max_length=25, verbose_name='Первый пункт меню')),
                ('second_menu', models.TextField(max_length=25, verbose_name='Второй пункт меню')),
                ('third_menu', models.TextField(max_length=25, verbose_name='Третий пункт меню')),
                ('fourth_menu', models.TextField(max_length=25, verbose_name='Четвертый пункт меню')),
                ('fifth_menu', models.TextField(max_length=25, verbose_name='Пятый пункт меню')),
                ('author', models.TextField(max_length=50, verbose_name='Автор')),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.TextField(max_length=30, verbose_name='Название таблицы')),
                ('table', models.TextField(verbose_name='Таблица')),
                ('graph_skills', models.ImageField(upload_to='images_db/%Y/%m/%d', verbose_name='График по скиллам')),
            ],
        ),
        migrations.AddField(
            model_name='lastvacancymodel',
            name='name_vacancy_to_parse',
            field=models.TextField(default=1, max_length=15, verbose_name='Вакансия для парсинга'),
            preserve_default=False,
        ),
    ]
